apiVersion: v1
kind: Pod
metadata:
  name: nginx-volume-pvc
  namespace: pv-test
spec:
  containers:
  - name: nginx-pvc
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: html-pvc         #自定义名的引用
      mountPath: /usr/share/nginx/html/
  volumes:               #这里是选择volume的类型
  - name: html-pvc           #自定义名
    persistentVolumeClaim:
      claimName: nfs-pvc     #我们刚才定义的pvc名