kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"  #---需要与上面创建的storageclass的名称一致
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi