apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: default
spec:
  replicas: 5
  minReadySeconds: 10
  strategy:
    rollingUpdate:                  #滚动策略
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: myapp
      rel: stable
  template:
    metadata:
      labels:
        app: myapp
        rel: stable
    spec:
      containers:
      - name: myapp
        image: nginx:1.16
        ports:
        - containerPort: 80
          name: http
        readinessProbe:             #就绪探针
          periodSeconds: 1
          httpGet:
            path: /
            port: http
