apiVersion: v1
kind: Pod
metadata:
  name: secret-dotfiles-pod
spec:
  volumes:
  - name: secret-volume
    secret:
      secretName: db-user-pass
      items:
      - key: username.txt                  #secrets中key的名字
        path: username                     #希望映射在Pod中的名字
      - key: password.txt
        path: password
  containers:
  - name: dotfile-test-container
    image: redis
    volumeMounts:
    - name: secret-volume
      readOnly: true
      mountPath: "/etc/secret-volume"