apiVersion: v1
kind: Pod
metadata:
 name: nginx
 namespace: config
spec:
 containers:
 - name: nginx
   image: nginx
   env:
   -  name: nginx_host
      valueFrom:
        configMapKeyRef:                 #从configmap中读取
          key: redis_host
          name: filebeat-cfg
   -  name: nginx_log_level
      valueFrom:
        configMapKeyRef:
          key: log_level
          name: filebeat-cfg
   -  name: nginx_static_value            #静态配置
      value: "123123"